ALTER TABLE trading_agents
    ADD COLUMN IF NOT EXISTS agent_role VARCHAR(50) DEFAULT 'QUANT_RESEARCHER',
    ADD COLUMN IF NOT EXISTS system_prompt TEXT,
    ADD COLUMN IF NOT EXISTS last_reasoning TEXT,
    ADD COLUMN IF NOT EXISTS last_confidence NUMERIC(10,4),
    ADD COLUMN IF NOT EXISTS total_executions INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS successful_executions INTEGER DEFAULT 0;
