package com.QuantPlatformApplication.QuantPlatformApplication.service;

import com.QuantPlatformApplication.QuantPlatformApplication.model.entity.Alert;
import com.QuantPlatformApplication.QuantPlatformApplication.repository.AlertRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Alert Service — Manages risk alerts and notifications.
 *
 * Alerts are generated by the RiskEngineService when thresholds
 * are breached. This service handles retrieval and acknowledgement.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AlertService {

    private final AlertRepository alertRepo;

    public List<Alert> getUnacknowledged() {
        return alertRepo.findByAcknowledgedFalseOrderByCreatedAtDesc();
    }

    public List<Alert> getAll() {
        return alertRepo.findAllByOrderByCreatedAtDesc();
    }

    public Alert acknowledge(Long id) {
        Alert alert = alertRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Alert not found: " + id));
        alert.setAcknowledged(true);
        return alertRepo.save(alert);
    }

    public Alert create(String type, String severity, String symbol, String message) {
        Alert alert = new Alert();
        alert.setAlertType(type);
        alert.setSeverity(severity);
        alert.setSymbol(symbol);
        alert.setMessage(message);
        log.info("Alert created: [{}] {} — {}", severity, type, message);
        return alertRepo.save(alert);
    }
}
